---
  dependency:
    name: galaxy
  driver:
    name: vagrant
    provider:
      name: libvirt
  platforms:
    - name: instance
      box: centos/7
      cpus: 1
      memory: 2048
  provisioner:
    name: ansible
  verifier:
    name: ansible
  lint: |
    set -e
    ansible-lint .
...